WIP: transaction attribution
encrypted-dev/userbase pull request #202
Opened 2020-08-30 16:05 UTC by shamblesides

2020-08-30 19:50 UTC, shamblesides commented on src/userbase-js/src/ws.js
> +              const databaseWritersMap = message.dbWriters && message.dbWriters.reduce((map, { userId, username }) => map.set(userId, username), new Map)
Maybe this should be a property on the database object, because I could use it when building a new bundle.

2020-08-30 19:51 UTC, shamblesides commented on src/userbase-js/src/ws.js
> +            userId: 'TODO',
Need to get this somehow.

2020-08-30 19:52 UTC, shamblesides commented on src/userbase-server/db.js
> +  connections.push(transaction)
I just noticed that Connections.push seems to only accept one argument. So I just removed the second one.

2020-08-30 19:52 UTC, shamblesides commented on src/userbase-server/server.js
> +        connections.push(transaction)
Another example of Connections.push only needing one argument

2020-08-31 19:27 UTC, shamblesides commented on src/userbase-server/db.js
> +  transaction['username'] = (await userPromise).username
Does this make sense? Or should I be sending over the username by some other means?

2020-09-08 03:14 UTC, j-berman requested changes
Looks great!!! Included some minor comments.

Also, nice use of Set() to avoid re-querying for users

2020-09-08 15:25 UTC, shamblesides commented on src/userbase-js/src/ws.js
> +                  database.userIdsByUsername.set(username, userId)
Good catch. I was using it in an older revision but not anymore

2020-09-08 15:49 UTC, shamblesides commented on src/userbase-js/src/ws.js
> +                  database.userIdsByUsername.set(username, userId)
Fixed

2020-09-08 15:49 UTC, shamblesides commented on src/userbase-js/src/ws.js
> +      ? [...database.usernamesByUserId.keys()].join(',')
Fixed

2020-09-08 15:50 UTC, shamblesides commented on src/userbase-server/ws.js
> +                if (userId != null) {
Good point. Fixed

2020-09-08 15:50 UTC, shamblesides commented on src/userbase-server/db.js
> +      await s3.upload(dbWritersParams).promise()
Done

2020-09-08 15:50 UTC, shamblesides commented on src/userbase-server/db.js
> +          // built with a client SDK that didn't include the writers array yet.
Agreed. Fixed

2020-09-08 15:50 UTC, shamblesides commented on src/userbase-server/db.js
> +        const writersObject = await s3.getObject(writersParams).promise()
Done

2020-09-08 17:06 UTC, shamblesides commented on src/userbase-server/ws.js
> +                if (userId != null) {
Actually this seems to cause a problem. Sometimes a "Rollback" is in the transaction log, and this doesn't have a user-id attached, so this fails. What should I do?

2020-09-08 22:26 UTC, j-berman commented on src/userbase-server/ws.js
> +                if (userId != null) {
Great point! So actually would have been a less safe check. This should do the trick:

```
if (database.attribution && transactionLogResponse.Items[i].command !== 'Rollback') {
    if (!userId) throw new Error('Missing attribution')
    else writerUserIds.add(userId)
}
```

2020-09-08 22:43 UTC, shamblesides commented on src/userbase-server/ws.js
> +                if (userId != null) {
Done! I think that's everything

2020-09-08 22:52 UTC, j-berman approved these changes

2020-09-08 22:53 UTC, merged